In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Raw data folder
RAW_PATH = "../data/raw"

# File paths
sales_file = os.path.join(RAW_PATH, "sales.csv")
customers_file = os.path.join(RAW_PATH, "customers.json")
products_file = os.path.join(RAW_PATH, "products.csv")

# Load datasets
sales = pd.read_csv(sales_file)
customers = pd.read_json(customers_file)
products = pd.read_csv(products_file)

print("All datasets loaded successfully.")

All datasets loaded successfully.

In [3]:
print("Sales:", sales.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)

Sales: (10000, 6)
Customers: (1100, 6)
Products: (50, 3)

In [6]:
# DATA PROFILING - PART 1
# Basic Structure & Data Types
datasets = {
    "SALES": sales,
    "CUSTOMERS": customers,
    "PRODUCTS": products
}

for name, df in datasets.items():

    print("\n" + "=" * 60)
    print(f"{name} DATASET")
    print("=" * 60)

    print("\nRows:", df.shape[0])
    print("Columns:", df.shape[1])

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

============================================================
SALES DATASET
============================================================

Rows: 10000
Columns: 6

Column Names:
['SaleID', 'ProductID', 'CustomerID', 'SalesAmount', 'Quantity', 'Timestamp']

Data Types:
SaleID             str
ProductID        int64
CustomerID         str
SalesAmount    float64
Quantity       float64
Timestamp          str
dtype: object

============================================================
CUSTOMERS DATASET
============================================================

Rows: 1100
Columns: 6

Column Names:
['CustomerID', 'FirstName', 'LastName', 'Gender', 'Region', 'SSN']

Data Types:
CustomerID    str
FirstName     str
LastName      str
Gender        str
Region        str
SSN           str
dtype: object

============================================================
PRODUCTS DATASET
============================================================

Rows: 50
Columns: 3

Column Names:
['ProductID', 'ProductName', 'Category']

Data Types:
ProductID      int64
ProductName      str
Category         str
dtype: object

In [7]:
# ============================================
# DATA PROFILING - PART 1
# Missing Value Analysis
# ============================================

for name, df in datasets.items():

    print("\n" + "=" * 60)
    print(f"{name} DATASET")
    print("=" * 60)

    missing = df.isnull().sum()
    missing_pct = (missing / len(df) * 100).round(2)

    missing_summary = pd.DataFrame({
        "Missing Count": missing,
        "Missing %": missing_pct
    })

    display(missing_summary)

============================================================
SALES DATASET
============================================================

             Missing Count  Missing %
SaleID                   0       0.00
ProductID                0       0.00
CustomerID               0       0.00
SalesAmount            497       4.97
Quantity               113       1.13
Timestamp                0       0.00

============================================================
CUSTOMERS DATASET
============================================================

            Missing Count  Missing %
CustomerID              0       0.00
FirstName               0       0.00
LastName              320      29.09
Gender                  0       0.00
Region                 69       6.27
SSN                     0       0.00

============================================================
PRODUCTS DATASET
============================================================

             Missing Count  Missing %
ProductID                0        0.0
ProductName              0        0.0
Category                 0        0.0

In [8]:
# ============================================
# DATA PROFILING - PART 1
# Duplicate Analysis
# ============================================

for name, df in datasets.items():

    print("\n" + "=" * 60)
    print(f"{name} DATASET")
    print("=" * 60)

    print("Duplicate rows:", df.duplicated().sum())

============================================================
SALES DATASET
============================================================
Duplicate rows: 0

============================================================
CUSTOMERS DATASET
============================================================
Duplicate rows: 100

============================================================
PRODUCTS DATASET
============================================================
Duplicate rows: 0

In [9]:
# ============================================
# KEY ID DUPLICATE CHECK
# ============================================

print("Duplicate SaleIDs:", sales["SaleID"].duplicated().sum())
print("Duplicate CustomerIDs:", customers["CustomerID"].duplicated().sum())
print("Duplicate ProductIDs:", products["ProductID"].duplicated().sum())

Duplicate SaleIDs: 0
Duplicate CustomerIDs: 100
Duplicate ProductIDs: 0

In [10]:
# ============================================
# DATA PROFILING - PART 2
# Values & Statistics
# ============================================

for name, df in datasets.items():

    print("\n" + "=" * 60)
    print(f"{name} DATASET")
    print("=" * 60)

    # Unique values
    print("\n--- UNIQUE VALUES ---")
    print(df.nunique())

    # Numerical statistics
    numeric_columns = df.select_dtypes(include=np.number).columns

    if len(numeric_columns) > 0:
        print("\n--- NUMERICAL SUMMARY ---")
        display(df[numeric_columns].describe())

    # Categorical values
    categorical_columns = df.select_dtypes(
        include=["object", "string"]
    ).columns

    if len(categorical_columns) > 0:
        print("\n--- CATEGORICAL VALUES ---")

        for column in categorical_columns:
            print(f"\n{column}:")
            print(df[column].value_counts(dropna=False))

============================================================
SALES DATASET
============================================================

--- UNIQUE VALUES ---
SaleID         10000
ProductID         50
CustomerID      1000
SalesAmount     9291
Quantity          50
Timestamp       9803
dtype: int64

--- NUMERICAL SUMMARY ---

          ProductID   SalesAmount     Quantity
count  10000.000000   9503.000000  9887.000000
mean    1024.431100   1436.999871    25.231617
std       14.515499   4874.463101    14.363280
min     1000.000000     50.180000     1.000000
25%     1012.000000    534.470000    13.000000
50%     1025.000000   1015.070000    25.000000
75%     1037.000000   1517.140000    38.000000
max     1049.000000  79783.400000    50.000000

--- CATEGORICAL VALUES ---

SaleID:
SaleID
c0078cd1-3ddc-439a-b41d-7498e8e75e62    1
be8532af-16b7-432c-a13d-4c6e6836d12d    1
8666f277-cc58-4fde-9d58-697da9e040f2    1
383e0a2b-7e00-454e-a269-b2f73ecd33f2    1
d9a7f974-9572-48dd-aa36-3f96b280dfc7    1
                                       ..
fac6d025-7dac-43b5-a2f9-f76730d9ac48    1
2244ad15-c624-4432-8f4f-3b4966c690b0    1
9b406983-3513-41e2-bb07-837c9c0e1957    1
a8070acd-841e-4bf8-948d-06be216cca68    1
6930980f-c919-4b7b-aada-ee10e2decf1d    1
Name: count, Length: 10000, dtype: int64

CustomerID:
CustomerID
C0517    28
C0965    27
C0780    26
C0835    25
C0742    25
         ..
C0347     2
C0455     2
C0928     2
C0159     2
C0975     1
Name: count, Length: 1000, dtype: int64

Timestamp:
Timestamp
2024-06-05T02:20:00    3
2024-06-11T21:00:00    3
2024-07-05T00:56:00    3
2024-10-27T15:44:00    3
2024-07-30T18:56:00    3
                      ..
2024-10-06T18:50:00    1
2024-08-21T07:47:00    1
2024-09-16T16:21:00    1
2024-06-07T02:21:00    1
2024-10-02T22:52:00    1
Name: count, Length: 9803, dtype: int64

============================================================
CUSTOMERS DATASET
============================================================

--- UNIQUE VALUES ---
CustomerID    1000
FirstName      318
LastName       400
Gender           6
Region          10
SSN           1000
dtype: int64

--- CATEGORICAL VALUES ---

CustomerID:
CustomerID
C0023    2
C0026    2
C0047    2
C0048    2
C0050    2
        ..
C0996    1
C0997    1
C0998    1
C0999    1
C1000    1
Name: count, Length: 1000, dtype: int64

FirstName:
FirstName
David          39
John           34
Michael        31
Christopher    28
Robert         27
               ..
Patrick         1
Kiara           1
Ann             1
Felicia         1
Alexandra       1
Name: count, Length: 318, dtype: int64

LastName:
LastName
NaN         320
Smith        24
Williams     17
Miller       12
Johnson      10
           ...
Mcclure       1
Mcmillan      1
Graham        1
Howe          1
Fox           1
Name: count, Length: 401, dtype: int64

Gender:
Gender
M         313
Male      278
male      272
F          88
female     82
Female     67
Name: count, dtype: int64

Region:
Region
NY             119
Californiya    113
Texaz          111
Ohho           105
New York       103
Texas          100
california      97
New Yorkk       96
Nw York         96
Ohio            91
NaN             69
Name: count, dtype: int64

SSN:
SSN
914-9819-50    2
929/20/0753    2
075643618      2
466.83.1539    2
556/57/7221    2
              ..
599/60/1108    1
079-89-1050    1
070190887      1
514/78/8515    1
796-93-4918    1
Name: count, Length: 1000, dtype: int64

============================================================
PRODUCTS DATASET
============================================================

--- UNIQUE VALUES ---
ProductID      50
ProductName    50
Category        4
dtype: int64

--- NUMERICAL SUMMARY ---

        ProductID
count    50.00000
mean   1024.50000
std      14.57738
min    1000.00000
25%    1012.25000
50%    1024.50000
75%    1036.75000
max    1049.00000

--- CATEGORICAL VALUES ---

ProductName:
ProductName
Washing Machine        1
Refrigerator           1
Blender                1
Microwave              1
Vacuum Cleaner         1
Sofa                   1
Table                  1
Chair                  1
Bed                    1
Cupboard               1
Laptop                 1
Smartphone             1
Headphones             1
Tablet                 1
Camera                 1
Smartwatch             1
Bluetooth Speaker      1
TV                     1
Monitor                1
Printer                1
Keyboard               1
Mouse                  1
Game Console           1
Smart Home Device      1
External Hard Drive    1
Webcam                 1
Projector              1
Drone                  1
VR Headset             1
Smart Glasses          1
Action Figure          1
Board Game             1
Doll                   1
Puzzle                 1
Lego Set               1
Toy Car                1
Building Blocks        1
Stuffed Animal         1
Play-Doh               1
Kite                   1
RC Car                 1
Toy Train              1
Magic Kit              1
Marbles                1
Barbie Doll            1
Toy Kitchen Set        1
Bicycle                1
Swing                  1
Educational Game       1
Jigsaw Puzzle          1
Name: count, dtype: int64

Category:
Category
Electronics        20
Toys               20
Home Appliances     5
Furniture           5
Name: count, dtype: int64

In [11]:
# ============================================
# FINAL RAW DATA VALIDATION
# ============================================

print("=" * 60)
print("SALES DATA VALIDATION")
print("=" * 60)

# Check ID relationships
print("\n--- REFERENTIAL INTEGRITY ---")

missing_product_ids = ~sales["ProductID"].isin(products["ProductID"])
missing_customer_ids = ~sales["CustomerID"].isin(customers["CustomerID"])

print("Sales with missing ProductID reference:",
      missing_product_ids.sum())

print("Sales with missing CustomerID reference:",
      missing_customer_ids.sum())

# Check numeric values
print("\n--- NUMERIC VALUE CHECKS ---")

print("Negative SalesAmount:",
      (sales["SalesAmount"] < 0).sum())

print("Zero SalesAmount:",
      (sales["SalesAmount"] == 0).sum())

print("Negative Quantity:",
      (sales["Quantity"] < 0).sum())

print("Zero Quantity:",
      (sales["Quantity"] == 0).sum())

# Check timestamp conversion
print("\n--- TIMESTAMP CHECK ---")

timestamp_check = pd.to_datetime(
    sales["Timestamp"],
    errors="coerce"
)

print("Invalid timestamps:",
      timestamp_check.isna().sum())

print("\nValidation completed.")

============================================================
SALES DATA VALIDATION
============================================================

--- REFERENTIAL INTEGRITY ---
Sales with missing ProductID reference: 0
Sales with missing CustomerID reference: 0

--- NUMERIC VALUE CHECKS ---
Negative SalesAmount: 0
Zero SalesAmount: 0
Negative Quantity: 0
Zero Quantity: 0

--- TIMESTAMP CHECK ---
Invalid timestamps: 0

Validation completed.

In [12]:
# ============================================
# SALES DATA CLEANING - INITIAL COPY
# ============================================

sales_clean = sales.copy()

print("Original Sales rows:", len(sales))
print("Working Sales rows:", len(sales_clean))

Original Sales rows: 10000
Working Sales rows: 10000

In [13]:
# ============================================
# SALES CLEANING - MISSING VALUE ANALYSIS
# ============================================

print("Missing SalesAmount:", sales_clean["SalesAmount"].isna().sum())
print("Missing Quantity:", sales_clean["Quantity"].isna().sum())

# Check whether both are missing in the same transaction
both_missing = (
    sales_clean["SalesAmount"].isna() &
    sales_clean["Quantity"].isna()
).sum()

print("Both SalesAmount and Quantity missing:", both_missing)

# Check each case separately
print("Only SalesAmount missing:",
      (sales_clean["SalesAmount"].isna() &
       sales_clean["Quantity"].notna()).sum())

print("Only Quantity missing:",
      (sales_clean["Quantity"].isna() &
       sales_clean["SalesAmount"].notna()).sum())

Missing SalesAmount: 497
Missing Quantity: 113
Both SalesAmount and Quantity missing: 7
Only SalesAmount missing: 490
Only Quantity missing: 106

In [14]:
# ============================================
# SALES CLEANING - QUANTITY ANALYSIS
# ============================================

print("Quantity statistics:")
display(sales_clean["Quantity"].describe())

print("\nQuantity value counts:")
display(sales_clean["Quantity"].value_counts().sort_index())

Quantity statistics:

count    9887.000000
mean       25.231617
std        14.363280
min         1.000000
25%        13.000000
50%        25.000000
75%        38.000000
max        50.000000
Name: Quantity, dtype: float64

Quantity value counts:

Quantity
1.0     185
2.0     200
3.0     200
4.0     215
5.0     205
6.0     177
7.0     179
8.0     234
9.0     221
10.0    196
11.0    195
12.0    205
13.0    190
14.0    228
15.0    196
16.0    192
17.0    213
18.0    180
19.0    224
20.0    180
21.0    194
22.0    206
23.0    206
24.0    220
25.0    213
26.0    183
27.0    209
28.0    190
29.0    201
30.0    219
31.0    188
32.0    177
33.0    184
34.0    215
35.0    186
36.0    194
37.0    199
38.0    203
39.0    174
40.0    208
41.0    176
42.0    210
43.0    185
44.0    191
45.0    186
46.0    180
47.0    198
48.0    186
49.0    186
50.0    205
Name: count, dtype: int64

In [15]:
# ============================================
# SALES CLEANING - MISSING QUANTITY BY PRODUCT
# ============================================

missing_quantity = sales_clean[sales_clean["Quantity"].isna()]

print("Missing Quantity records:", len(missing_quantity))

print("\nMissing Quantity by ProductID:")
display(
    missing_quantity["ProductID"]
    .value_counts()
    .sort_index()
)

Missing Quantity records: 113

Missing Quantity by ProductID:

ProductID
1000    3
1001    1
1002    2
1003    2
1004    2
1005    2
1007    2
1009    2
1010    2
1011    5
1012    1
1013    4
1014    3
1015    3
1016    3
1017    3
1018    1
1019    2
1020    1
1021    1
1022    2
1023    5
1024    3
1025    1
1026    4
1027    4
1028    2
1030    2
1031    4
1032    3
1033    1
1034    1
1035    2
1036    1
1037    3
1038    1
1039    3
1040    2
1041    8
1042    1
1044    4
1045    1
1046    3
1047    3
1048    1
1049    3
Name: count, dtype: int64

In [17]:
# Checking whether every product with missing quantity has enough non-missing quantity observations

product_quantity_stats = (
    sales_clean.groupby("ProductID")["Quantity"]
    .agg(["count", "median"])
    .reset_index()
)

print("Product-level quantity statistics:")
display(product_quantity_stats)

Product-level quantity statistics:

    ProductID  count  median
0        1000    207    26.0
1        1001    196    25.0
2        1002    217    25.0
3        1003    190    26.5
4        1004    208    23.5
5        1005    194    23.0
6        1006    207    26.0
7        1007    210    27.0
8        1008    208    25.0
9        1009    212    26.0
10       1010    210    24.0
11       1011    202    22.0
12       1012    194    25.5
13       1013    207    24.0
14       1014    191    26.0
15       1015    178    24.0
16       1016    185    27.0
17       1017    199    22.0
18       1018    197    23.0
19       1019    172    25.0
20       1020    198    23.0
21       1021    175    25.0
22       1022    187    25.0
23       1023    169    26.0
24       1024    185    25.0
25       1025    185    25.0
26       1026    192    25.0
27       1027    224    25.0
28       1028    178    25.0
29       1029    201    27.0
30       1030    211    23.0
31       1031    215    27.0
32       1032    229    24.0
33       1033    218    25.0
34       1034    192    22.5
35       1035    200    25.0
36       1036    187    27.0
37       1037    194    24.0
38       1038    209    26.0
39       1039    197    24.0
40       1040    196    25.0
41       1041    183    28.0
42       1042    195    22.0
43       1043    195    24.0
44       1044    174    26.0
45       1045    209    25.0
46       1046    207    27.0
47       1047    211    26.0
48       1048    203    24.0
49       1049    184    29.0

In [18]:
# ============================================
# SALES DATA CLEANING
# ============================================

# 1. Remove records with missing SalesAmount
sales_clean = sales_clean.dropna(subset=["SalesAmount"]).copy()

# 2. Fill missing Quantity using ProductID median
product_quantity_median = (
    sales_clean.groupby("ProductID")["Quantity"]
    .transform("median")
)

sales_clean["Quantity"] = sales_clean["Quantity"].fillna(
    product_quantity_median
)

# 3. Convert Timestamp to datetime
sales_clean["Timestamp"] = pd.to_datetime(
    sales_clean["Timestamp"],
    errors="coerce"
)

print("Sales cleaning completed.")
print("Remaining rows:", len(sales_clean))
print("Missing SalesAmount:", sales_clean["SalesAmount"].isna().sum())
print("Missing Quantity:", sales_clean["Quantity"].isna().sum())
print("Invalid Timestamp:", sales_clean["Timestamp"].isna().sum())

Sales cleaning completed.
Remaining rows: 9503
Missing SalesAmount: 0
Missing Quantity: 0
Invalid Timestamp: 0

In [19]:
# ============================================
# SALES CLEANING - FINAL VALIDATION
# ============================================

print("========== CLEANED SALES VALIDATION ==========")

print("\nDuplicate SaleIDs:",
      sales_clean["SaleID"].duplicated().sum())

print("Missing ProductIDs:",
      sales_clean["ProductID"].isna().sum())

print("Missing CustomerIDs:",
      sales_clean["CustomerID"].isna().sum())

print("Negative SalesAmount:",
      (sales_clean["SalesAmount"] < 0).sum())

print("Zero SalesAmount:",
      (sales_clean["SalesAmount"] == 0).sum())

print("Negative Quantity:",
      (sales_clean["Quantity"] < 0).sum())

print("Zero Quantity:",
      (sales_clean["Quantity"] == 0).sum())

print("Invalid Timestamps:",
      sales_clean["Timestamp"].isna().sum())

print("\nFinal Sales rows:", len(sales_clean))

========== CLEANED SALES VALIDATION ==========

Duplicate SaleIDs: 0
Missing ProductIDs: 0
Missing CustomerIDs: 0
Negative SalesAmount: 0
Zero SalesAmount: 0
Negative Quantity: 0
Zero Quantity: 0
Invalid Timestamps: 0

Final Sales rows: 9503

In [20]:
# ============================================
# CUSTOMERS DATA CLEANING - INITIAL COPY
# ============================================

customers_clean = customers.copy()

print("Original Customer rows:", len(customers))
print("Working Customer rows:", len(customers_clean))

Original Customer rows: 1100
Working Customer rows: 1100

In [21]:
# ============================================
# CUSTOMER CLEANING - DUPLICATE ANALYSIS
# ============================================

duplicate_customers = customers_clean[
    customers_clean["CustomerID"].duplicated(keep=False)
].sort_values("CustomerID")

print("Duplicate CustomerID records:",
      duplicate_customers["CustomerID"].duplicated().sum())

print("\nDuplicate CustomerID values:")
display(
    duplicate_customers["CustomerID"]
    .value_counts()
    .sort_index()
)

print("\nSample duplicate records:")
display(duplicate_customers.head(20))

Duplicate CustomerID records: 100

Duplicate CustomerID values:

CustomerID
C0023    2
C0026    2
C0047    2
C0048    2
C0050    2
        ..
C0939    2
C0965    2
C0966    2
C0971    2
C0989    2
Name: count, Length: 100, dtype: int64

Sample duplicate records:

     CustomerID FirstName   LastName  Gender   Region          SSN
22        C0023     Grant   Bartlett    male     Ohio  914-9819-50
1000      C0023     Grant   Bartlett    male     Ohio  914-9819-50
25        C0026     Jesse  Wilkerson    male       NY  929/20/0753
1001      C0026     Jesse  Wilkerson    male       NY  929/20/0753
46        C0047      Seth       Hess    Male    Texas    075643618
1002      C0047      Seth       Hess    Male    Texas    075643618
47        C0048     Frank       Ross       M     Ohho  466.83.1539
1003      C0048     Frank       Ross       M     Ohho  466.83.1539
49        C0050  Kimberly     Wright  female  Nw York  556/57/7221
1004      C0050  Kimberly     Wright  female  Nw York  556/57/7221
1005      C0051     David        NaN    Male      NaN  709.24.5509
50        C0051     David        NaN    Male      NaN  709.24.5509
62        C0063    Latoya        NaN  female     Ohho  575-57-9346
1006      C0063    Latoya        NaN  female     Ohho  575-57-9346
1007      C0067      Eric     Morris    male       NY  192-18-1825
66        C0067      Eric     Morris    male       NY  192-18-1825
1008      C0127     Frank     Turner    Male      NaN  817-84-4697
126       C0127     Frank     Turner    Male      NaN  817-84-4697
1009      C0128      Tina        NaN  Female     Ohio  387/15/2762
127       C0128      Tina        NaN  Female     Ohio  387/15/2762

In [22]:
sales_clean["SaleID"]      # keep as string
sales_clean["CustomerID"]  # keep as string
customers_clean["CustomerID"]  # keep as string

0       C0001
1       C0002
2       C0003
3       C0004
4       C0005
        ...
1095    C0939
1096    C0965
1097    C0966
1098    C0971
1099    C0989
Name: CustomerID, Length: 1100, dtype: str

In [23]:
# ============================================
# CUSTOMER CLEANING - DUPLICATE CUSTOMER IDs
# ============================================

duplicate_ids = customers_clean[
    customers_clean["CustomerID"].duplicated(keep=False)
].sort_values("CustomerID")

print("Total duplicate CustomerID records:",
      duplicate_ids.shape[0])

print("\nNumber of unique duplicated CustomerIDs:",
      duplicate_ids["CustomerID"].nunique())

print("\nSample duplicate customer records:")
display(duplicate_ids.head(20))

Total duplicate CustomerID records: 200

Number of unique duplicated CustomerIDs: 100

Sample duplicate customer records:

     CustomerID FirstName   LastName  Gender   Region          SSN
22        C0023     Grant   Bartlett    male     Ohio  914-9819-50
1000      C0023     Grant   Bartlett    male     Ohio  914-9819-50
25        C0026     Jesse  Wilkerson    male       NY  929/20/0753
1001      C0026     Jesse  Wilkerson    male       NY  929/20/0753
46        C0047      Seth       Hess    Male    Texas    075643618
1002      C0047      Seth       Hess    Male    Texas    075643618
47        C0048     Frank       Ross       M     Ohho  466.83.1539
1003      C0048     Frank       Ross       M     Ohho  466.83.1539
49        C0050  Kimberly     Wright  female  Nw York  556/57/7221
1004      C0050  Kimberly     Wright  female  Nw York  556/57/7221
1005      C0051     David        NaN    Male      NaN  709.24.5509
50        C0051     David        NaN    Male      NaN  709.24.5509
62        C0063    Latoya        NaN  female     Ohho  575-57-9346
1006      C0063    Latoya        NaN  female     Ohho  575-57-9346
1007      C0067      Eric     Morris    male       NY  192-18-1825
66        C0067      Eric     Morris    male       NY  192-18-1825
1008      C0127     Frank     Turner    Male      NaN  817-84-4697
126       C0127     Frank     Turner    Male      NaN  817-84-4697
1009      C0128      Tina        NaN  Female     Ohio  387/15/2762
127       C0128      Tina        NaN  Female     Ohio  387/15/2762

In [24]:
# ============================================
# CUSTOMER CLEANING - REMOVE DUPLICATES
# ============================================

before = len(customers_clean)

customers_clean = customers_clean.drop_duplicates(
    subset=["CustomerID"],
    keep="first"
).copy()

after = len(customers_clean)

print("Rows before deduplication:", before)
print("Rows after deduplication:", after)
print("Duplicate CustomerIDs remaining:",
      customers_clean["CustomerID"].duplicated().sum())

Rows before deduplication: 1100
Rows after deduplication: 1000
Duplicate CustomerIDs remaining: 0

In [25]:
# ============================================
# CUSTOMER CLEANING - MISSING VALUES
# ============================================

print("Missing values after deduplication:")
print(customers_clean.isnull().sum())

Missing values after deduplication:
CustomerID      0
FirstName       0
LastName      290
Gender          0
Region         62
SSN             0
dtype: int64

In [26]:
# ============================================
# CUSTOMER CLEANING - HANDLE MISSING VALUES
# ============================================

customers_clean["LastName"] = customers_clean["LastName"].fillna("Unknown")
customers_clean["Region"] = customers_clean["Region"].fillna("Unknown")

print("Missing values after treatment:")
print(customers_clean.isnull().sum())

Missing values after treatment:
CustomerID    0
FirstName     0
LastName      0
Gender        0
Region        0
SSN           0
dtype: int64

In [27]:
# ============================================
# CUSTOMER CLEANING - GENDER STANDARDIZATION
# ============================================

print("Gender values before standardization:")
print(customers_clean["Gender"].value_counts())

Gender values before standardization:
Gender
M         285
male      249
Male      249
F          80
female     75
Female     62
Name: count, dtype: int64

In [28]:
# ============================================
# CUSTOMER CLEANING - STANDARDIZE GENDER
# ============================================

gender_mapping = {
    "M": "Male",
    "male": "Male",
    "Male": "Male",
    "F": "Female",
    "female": "Female",
    "Female": "Female"
}

customers_clean["Gender"] = customers_clean["Gender"].replace(gender_mapping)

print("Gender values after standardization:")
print(customers_clean["Gender"].value_counts())

Gender values after standardization:
Gender
Male      783
Female    217
Name: count, dtype: int64

In [29]:
# ============================================
# CUSTOMER CLEANING - REGION INSPECTION
# ============================================

print("Region values before standardization:")
print(customers_clean["Region"].value_counts(dropna=False))

Region values before standardization:
Region
Californiya    102
NY             102
Texaz          102
New York        96
Ohho            94
Texas           92
Nw York         92
california      90
New Yorkk       87
Ohio            81
Unknown         62
Name: count, dtype: int64

In [30]:
# ============================================
# CUSTOMER CLEANING - STANDARDIZE REGION
# ============================================

region_mapping = {
    "Californiya": "California",
    "california": "California",
    "NY": "New York",
    "Nw York": "New York",
    "New Yorkk": "New York",
    "Texaz": "Texas",
    "Ohho": "Ohio"
}

customers_clean["Region"] = customers_clean["Region"].replace(region_mapping)

print("Region values after standardization:")
print(customers_clean["Region"].value_counts())

Region values after standardization:
Region
New York      377
Texas         194
California    192
Ohio          175
Unknown        62
Name: count, dtype: int64

In [31]:
# ============================================
# FINAL CUSTOMER DATA VALIDATION
# ============================================

print("=" * 60)
print("CLEANED CUSTOMER DATA VALIDATION")
print("=" * 60)

print("\n--- STRUCTURE ---")
print("Final rows:", len(customers_clean))
print("Final columns:", len(customers_clean.columns))

print("\n--- DUPLICATES ---")
print("Duplicate CustomerIDs:",
      customers_clean["CustomerID"].duplicated().sum())
print("Duplicate rows:",
      customers_clean.duplicated().sum())

print("\n--- MISSING VALUES ---")
print(customers_clean.isnull().sum())

print("\n--- STANDARDIZED GENDER ---")
print(customers_clean["Gender"].value_counts())

print("\n--- STANDARDIZED REGION ---")
print(customers_clean["Region"].value_counts())

print("\nCustomer data validation completed.")

============================================================
CLEANED CUSTOMER DATA VALIDATION
============================================================

--- STRUCTURE ---
Final rows: 1000
Final columns: 6

--- DUPLICATES ---
Duplicate CustomerIDs: 0
Duplicate rows: 0

--- MISSING VALUES ---
CustomerID    0
FirstName     0
LastName      0
Gender        0
Region        0
SSN           0
dtype: int64

--- STANDARDIZED GENDER ---
Gender
Male      783
Female    217
Name: count, dtype: int64

--- STANDARDIZED REGION ---
Region
New York      377
Texas         194
California    192
Ohio          175
Unknown        62
Name: count, dtype: int64

Customer data validation completed.

In [32]:
# ============================================
# PRODUCT CLEANING - CREATE WORKING COPY
# ============================================

products_clean = products.copy()

print("Original Product rows:", len(products))
print("Working Product rows:", len(products_clean))

Original Product rows: 50
Working Product rows: 50

In [33]:
# ============================================
# PRODUCT CLEANING - STRUCTURE CHECK
# ============================================

print("=" * 60)
print("PRODUCT DATA STRUCTURE")
print("=" * 60)

print("\nRows:", products_clean.shape[0])
print("Columns:", products_clean.shape[1])

print("\nColumn Names:")
print(products_clean.columns.tolist())

print("\nData Types:")
print(products_clean.dtypes)

============================================================
PRODUCT DATA STRUCTURE
============================================================

Rows: 50
Columns: 3

Column Names:
['ProductID', 'ProductName', 'Category']

Data Types:
ProductID      int64
ProductName      str
Category         str
dtype: object

In [34]:
# ============================================
# PRODUCT CLEANING - MISSING VALUES
# ============================================

print("Missing values in Product dataset:")
print(products_clean.isnull().sum())

Missing values in Product dataset:
ProductID      0
ProductName    0
Category       0
dtype: int64

In [35]:
# ============================================
# PRODUCT CLEANING - DUPLICATE CHECK
# ============================================

print("Duplicate ProductIDs:",
      products_clean["ProductID"].duplicated().sum())

print("Duplicate product rows:",
      products_clean.duplicated().sum())

Duplicate ProductIDs: 0
Duplicate product rows: 0

In [36]:
# ============================================
# PRODUCT CLEANING - CATEGORY INSPECTION
# ============================================

print("Category values:")
print(products_clean["Category"].value_counts())

Category values:
Category
Electronics        20
Toys               20
Home Appliances     5
Furniture           5
Name: count, dtype: int64

In [37]:
# ============================================
# FINAL PRODUCT DATA VALIDATION
# ============================================

print("=" * 60)
print("CLEANED PRODUCT DATA VALIDATION")
print("=" * 60)

print("\n--- STRUCTURE ---")
print("Final rows:", len(products_clean))
print("Final columns:", len(products_clean.columns))

print("\n--- DUPLICATES ---")
print("Duplicate ProductIDs:",
      products_clean["ProductID"].duplicated().sum())
print("Duplicate rows:",
      products_clean.duplicated().sum())

print("\n--- MISSING VALUES ---")
print(products_clean.isnull().sum())

print("\n--- CATEGORIES ---")
print(products_clean["Category"].value_counts())

print("\nProduct data validation completed.")

============================================================
CLEANED PRODUCT DATA VALIDATION
============================================================

--- STRUCTURE ---
Final rows: 50
Final columns: 3

--- DUPLICATES ---
Duplicate ProductIDs: 0
Duplicate rows: 0

--- MISSING VALUES ---
ProductID      0
ProductName    0
Category       0
dtype: int64

--- CATEGORIES ---
Category
Electronics        20
Toys               20
Home Appliances     5
Furniture           5
Name: count, dtype: int64

Product data validation completed.

In [38]:
# ============================================
# ETL - CREATE PROCESSED DATA DIRECTORY
# ============================================

PROCESSED_PATH = "../data/processed"

os.makedirs(PROCESSED_PATH, exist_ok=True)

print("Processed data directory ready:")
print(os.path.abspath(PROCESSED_PATH))

Processed data directory ready:
c:\Users\MKDco\Desktop\case studied\Retail_Analytics_Project\data\processed

In [39]:
# ============================================
# ETL - EXPORT CLEANED DATASETS
# ============================================

sales_clean.to_csv(
    os.path.join(PROCESSED_PATH, "sales_clean.csv"),
    index=False
)

customers_clean.to_csv(
    os.path.join(PROCESSED_PATH, "customers_clean.csv"),
    index=False
)

products_clean.to_csv(
    os.path.join(PROCESSED_PATH, "products_clean.csv"),
    index=False
)

print("Cleaned datasets exported successfully.")
print("\nFiles created:")
print("- sales_clean.csv")
print("- customers_clean.csv")
print("- products_clean.csv")

Cleaned datasets exported successfully.

Files created:
- sales_clean.csv
- customers_clean.csv
- products_clean.csv

In [40]:
# ============================================
# ETL - VERIFY PROCESSED FILES
# ============================================

processed_files = [
    "sales_clean.csv",
    "customers_clean.csv",
    "products_clean.csv"
]

print("Processed files verification:")
print("=" * 50)

for file in processed_files:
    file_path = os.path.join(PROCESSED_PATH, file)
    df = pd.read_csv(file_path)

    print(f"\n{file}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("File exists:", os.path.exists(file_path))

print("\nETL export verification completed.")

Processed files verification:
==================================================

sales_clean.csv
Rows: 9503
Columns: 6
File exists: True

customers_clean.csv
Rows: 1000
Columns: 6
File exists: True

products_clean.csv
Rows: 50
Columns: 3
File exists: True

ETL export verification completed.

In [41]:
# ============================================
# CHECK SALEID LENGTH
# ============================================

sale_id_lengths = sales_clean["SaleID"].astype(str).str.len()

print("Maximum SaleID length:", sale_id_lengths.max())
print("Minimum SaleID length:", sale_id_lengths.min())

print("\nLongest SaleID values:")
print(
    sales_clean.loc[
        sale_id_lengths.nlargest(10).index,
        "SaleID"
    ].tolist()
)

Maximum SaleID length: 36
Minimum SaleID length: 36

Longest SaleID values:
['c0078cd1-3ddc-439a-b41d-7498e8e75e62', 'be8532af-16b7-432c-a13d-4c6e6836d12d', '8666f277-cc58-4fde-9d58-697da9e040f2', 'd9a7f974-9572-48dd-aa36-3f96b280dfc7', 'd71733ac-4fc4-42e6-ae48-c2150c8a92ae', 'b7475afb-27f7-46fe-8bcd-c099c178d17f', 'f5953c0c-e9bc-489a-9333-1e0c0a81d873', '427c33bb-dff7-4332-8d29-954728c713b1', '812ad61f-2e80-4b95-ae02-a91976bd2baa', 'a18dadb3-b2e6-476e-b2fb-b4a477721bf0']